[package]
name = "clouseau_query"
version = "0.3.1"
authors = ["Peter Hall <peterjoel@gmail.com>"]
edition = "2018"
license = "MIT"
description = "Internal dependency of clouseau"

[dependencies]
clouseau_core = { path = "../core", version = "0.3.1"}
itertools = "0.10"
